import type { CareerKnowledgeBase } from "@/types/careerKnowledgeBase";
import type { ResumeData, SkillsData } from "@/types/resume";

function findLink(kb: CareerKnowledgeBase, label: string): string | undefined {
  return kb.personal.links?.find((l) => l.label.toLowerCase() === label)?.url;
}

function toSkillsData(kb: CareerKnowledgeBase): SkillsData {
  const skills: SkillsData = {};
  for (const { category, items } of kb.technologies) {
    const key = category.toLowerCase();
    if (key.includes("backend"))
      skills.languages = [...(skills.languages ?? []), ...items];
    else if (key.includes("frontend"))
      skills.frameworks = [...(skills.frameworks ?? []), ...items];
    else if (key.includes("database"))
      skills.databases = [...(skills.databases ?? []), ...items];
    else if (key.includes("cloud"))
      skills.cloud = [...(skills.cloud ?? []), ...items];
    else skills.tools = [...(skills.tools ?? []), ...items];
  }
  return skills;
}

/**
 * Deterministically projects the full career knowledge base into the
 * ResumeData shape, with nothing trimmed or reworded. Used only to seed the
 * "Master Resume" baseline ResumeVersion shown for reference/diffing - the
 * actual tailored resumes are generated by Gemini directly from the
 * knowledge base (see resumeTailor.ts), not from this projection.
 */
export function careerKnowledgeBaseToResumeData(
  kb: CareerKnowledgeBase,
): ResumeData {
  return {
    basics: {
      name: kb.personal.fullName,
      title: kb.personal.headline,
      email: kb.personal.email,
      phone: kb.personal.phone ?? "",
      location: kb.personal.location,
      linkedin: findLink(kb, "linkedin"),
      github: findLink(kb, "github"),
      portfolio: findLink(kb, "portfolio"),
      summary: kb.personal.summary ?? "",
    },
    experience: kb.experience.map((entry) => ({
      company: entry.company,
      role: entry.role,
      location: entry.location,
      startDate: entry.startDate,
      endDate: entry.endDate ?? "Present",
      bullets: entry.achievements,
      technologies: entry.technologies,
    })),
    projects: kb.projects.map((project) => ({
      name: project.name,
      link: project.url,
      bullets: project.highlights,
      technologies: project.technologies,
    })),
    skills: toSkillsData(kb),
    education: kb.education.map((entry) => ({
      institution: entry.institution,
      degree: entry.degree,
      location: entry.location,
      startDate: entry.startDate,
      endDate: entry.endDate,
      gpa: entry.gpa,
      notes: entry.notes,
    })),
  };
}
